In [1]:
# Here are the libraries I am using
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from os import path
import json
import csv
import twitter

In [2]:
api = twitter.Api(consumer_key='VMEtmluCX5kbgdpxVGCQpKsU3',
                  consumer_secret='EE7IAgm84rzEaMYmxzDVFRqc0VG5TPCQ91PaExgn9tkv8WdrJ7',
                  access_token_key='894677768465731586-w4kRfckM6aRHvdEPwX7ycYCCXc9a2Y1',
                  access_token_secret='aup3PMyri8zRV66XKBcThxO08HSA3PSZfWvdKseC5JEPq',
                 sleep_on_rate_limit=True)

In [3]:
df_2015_SP = pd.read_csv('2017_SP_candidates.csv')

In [4]:
df_2015_SP.head(10)

,Unnamed: 0,name,gender,birth_date,party_name,post_label,elected,twitter_username,twitter_user_id
0,2,Stephen Kinnock,male,1970-01-01,Labour Party,Aberavon,True,SKinnock,722347303
1,3,Cen Phillips,male,1971,Liberal Democrats,Aberavon,False,CenLD,1872769464
2,4,Sadie Vidal,female,NaN,Conservative and Unionist Party,Aberavon,False,sadievidal,19447175
3,5,Guto Bebb,male,1968-10-09,Conservative and Unionist Party,Aberconwy,True,GutoAberconwy,752820350371717120
4,8,Emily Owen,Female,1995,Labour Party,Aberconwy,False,Emily4Aberconwy,92363214
5,10,Isobel Davidson,female,NaN,Liberal Democrats,Aberdeen North,False,isobeldavidson,1553831654
6,12,Grace O'Keeffe,female,NaN,Conservative and Unionist Party,Aberdeen North,False,Grace_E_OKeeffe,858789131622723584
7,13,Orr Vinegold,male,1988,Labour Party,Aberdeen North,False,OrrVinegoldLab,857290145795641344
8,15,Callum O'Dwyer,Male,NaN,Labour Party,Aberdeen South,False,callumjodwyer,65415768
9,16,Ross Thomson,male,1987-09-21,Conservative and Unionist Party,Aberdeen South,True,RossThomson_MP,539849453

In [5]:
list_id_2015_SP = df_2015_SP.twitter_user_id.tolist()

In [6]:
new_list_id = list_id_2015_SP

In [7]:
len(new_list_id)

1455

In [8]:
# list_id_2015_SP 1152
count = 1152
# dataset_15sp = []

In [ ]:
for _id in new_list_id[count:-1]:
    print(_id, count)
    Get_degree(userid = _id)
    
#     with open('neighbor_information49.csv', 'a') as myfile:
#         myfile.write('{}\n'.format(','.join(map(str,Get_degree(userid = _id)))))
    count = count +1
#         wr.writerow(Get_degree(userid = id))

114521927 1152
114521927 get 88 friends
114521927 get 88 friends done
368314502 1153
368314502 get 7738 friends
368314502 get 7738 friends done
140837603 1154
140837603 get 41 friends
140837603 get 41 friends done
114159336 1155
114159336 get 428 friends
114159336 get 428 friends done
2776689260 1156
2776689260 get 4082 friends
2776689260 get 4082 friends done
14284260 1157
14284260 get 14212 friends
14284260 get 14212 friends done
859370246393782272 1158
859370246393782272 get 38 friends
859370246393782272 get 38 friends done
4925049011 1159
4925049011 get 367 friends
4925049011 get 367 friends done
185790986 1160
185790986 get 5380 friends
185790986 get 5380 friends done
48030314 1161
48030314 get 346 friends
48030314 get 346 friends done
118048017 1162
118048017 get 215 friends
118048017 get 215 friends done
90646214 1163
90646214 get 11289 friends
90646214 get 11289 friends done
2230539338 1164
2230539338 get 8130 friends
2230539338 get 8130 friends done
112212596 1165
112212596 get 352 friends
112212596 get 352 friends done
860235925225340928 1166
860235925225340928 get 73 friends
860235925225340928 get 73 friends done
394638872 1167
394638872 get 1327 friends
394638872 get 1327 friends done
65357102 1168
65357102 get 34851 friends
65357102 get 34851 friends done
863568229725343744 1169
863568229725343744 get 13 friends
863568229725343744 get 13 friends done
112398730 1170
112398730 get 100305 friends
112398730 get 100305 friends done
555006697 1171
555006697 get 171 friends
555006697 get 171 friends done
68444494 1172
68444494 get 131 friends
68444494 get 131 friends done
759067032 1173
759067032 get 6557 friends
759067032 get 6557 friends done
208484718 1174
208484718 get 1083 friends
208484718 get 1083 friends done
3053609033 1175
3053609033 get 328 friends
3053609033 get 328 friends done
3699498077 1176
3699498077 get 665 friends
3699498077 get 665 friends done
75562171 1177
75562171 get 3454 friends
75562171 get 3454 friends done
90499799 1178
90499799 get 320 friends
90499799 get 320 friends done
172090468 1179
172090468 get 2376 friends
172090468 get 2376 friends done
389443487 1180
389443487 get 5870 friends
389443487 get 5870 friends done
141015432 1181
141015432 get 1202 friends
141015432 get 1202 friends done
20056279 1182
20056279 get 5420 friends
20056279 get 5420 friends done
43954039 1183
43954039 get 1306 friends
43954039 get 1306 friends done
2902135256 1184
2902135256 get 693 friends
2902135256 get 693 friends done
1395516325 1185
1395516325 get 1255 friends
1395516325 get 1255 friends done
2335638732 1186
2335638732 get 516 friends
2335638732 get 516 friends done
4600701923 1187
4600701923 get 17 friends
4600701923 get 17 friends done
558522066 1188
558522066 get 402 friends
558522066 get 402 friends done
113476721 1189
113476721 get 4159 friends
113476721 get 4159 friends done
860205568136556544 1190
860205568136556544 get 114 friends
860205568136556544 get 114 friends done
21174263 1191
21174263 get 3988 friends
21174263 get 3988 friends done
720207608615997440 1192
720207608615997440 get 88 friends
720207608615997440 get 88 friends done
36158689 1193
36158689 get 10355 friends
36158689 get 10355 friends done
20141120 1194
20141120 get 837 friends
20141120 get 837 friends done
18765853 1195
18765853 get 1223 friends
18765853 get 1223 friends done
137055756 1196
137055756 get 692 friends
137055756 get 692 friends done
2350948635 1197
2350948635 get 6424 friends
2350948635 get 6424 friends done
3252801106 1198
3252801106 get 1366 friends
3252801106 get 1366 friends done
417975170 1199
417975170 get 7645 friends
417975170 get 7645 friends done
764003293 1200
764003293 get 644 friends
764003293 get 644 friends done
574843120 1201
574843120 get 767 friends
574843120 get 767 friends done
921624025 1202
921624025 get 378 friends
921624025 get 378 friends done
65113456 1203
65113456 get 1414 friends
65113456 get 1414 friends done
2615199861 1204
2615199861 get 1093 friends
2615199861 get 1093 friends done
857617172666953728 1205
857617172666953728 get 235 friends
857617172666953728 get 235 friends done
397160160 1206
397160160 get 5016 friends
397160160 get 5016 friends done
2785648892 1207
2785648892 get 249 friends
2785648892 get 249 friends done
19126349 1208
19126349 get 294 friends
19126349 get 294 friends done
4831024203 1209
4831024203 with error
558445037 1210
558445037 get 8208 friends
558445037 get 8208 friends done
57057518 1211
57057518 get 8642 friends
57057518 get 8642 friends done
18449366 1212
18449366 get 187 friends
18449366 get 187 friends done
143739561 1213
143739561 get 13823 friends
143739561 get 13823 friends done
78291335 1214
78291335 get 258 friends
78291335 get 258 friends done
72531619 1215
72531619 get 2619 friends
72531619 get 2619 friends done
4418225835 1216
4418225835 get 17 friends
4418225835 get 17 friends done
3364523793 1217
3364523793 get 569 friends
3364523793 get 569 friends done
385415292 1218
385415292 get 814 friends
385415292 get 814 friends done
20428671 1219
20428671 get 8764 friends
20428671 get 8764 friends done
1722565140 1220
1722565140 get 884 friends
1722565140 get 884 friends done
168592013 1221
168592013 get 5988 friends
168592013 get 5988 friends done
257653019 1222
257653019 get 318 friends
257653019 get 318 friends done
100520303 1223
100520303 get 3439 friends
100520303 get 3439 friends done
121192398 1224
121192398 get 677 friends
121192398 get 677 friends done
70796349 1225
70796349 get 14416 friends
70796349 get 14416 friends done
1386916794 1226
1386916794 get 1581 friends
1386916794 get 1581 friends done
1190173345 1227
1190173345 get 1222 friends
1190173345 get 1222 friends done
160865889 1228
160865889 get 1365 friends
160865889 get 1365 friends done
859502127932198912 1229
859502127932198912 with error
121127090 1230
121127090 get 21480 friends
121127090 get 21480 friends done
495178605 1231
495178605 get 622 friends
495178605 get 622 friends done
198527033 1232
198527033 get 607 friends
198527033 get 607 friends done
33300246 1233
33300246 with error
50435415 1234
50435415 get 1082 friends
50435415 get 1082 friends done
105838665 1235
105838665 get 27012 friends
105838665 get 27012 friends done
554602188 1236
554602188 get 7758 friends
554602188 get 7758 friends done
50714939 1237
50714939 get 14687 friends
50714939 get 14687 friends done
3324653218 1238
3324653218 get 461 friends
3324653218 get 461 friends done
134066573 1239
134066573 get 371 friends
134066573 get 371 friends done
776022362 1240
776022362 get 10996 friends
776022362 get 10996 friends done
4635222568 1241
4635222568 get 292 friends
4635222568 get 292 friends done
416356558 1242
416356558 get 440 friends
416356558 get 440 friends done
1574883223 1243
1574883223 get 2559 friends
1574883223 get 2559 friends done
2920630870 1244
2920630870 get 212 friends
2920630870 get 212 friends done
748453510048518144 1245
748453510048518144 with error
616250395 1246
616250395 get 1091 friends
616250395 get 1091 friends done
19542502 1247
19542502 get 2595 friends
19542502 get 2595 friends done
1599131336 1248
1599131336 get 751 friends
1599131336 get 751 friends done
17484283 1249
17484283 get 6179 friends
17484283 get 6179 friends done
256212630 1250
256212630 get 354 friends
256212630 get 354 friends done
2406093795 1251
2406093795 get 8493 friends
2406093795 get 8493 friends done
861990959097278464 1252
861990959097278464 with error
147628329 1253
147628329 get 1101 friends
147628329 get 1101 friends done
92740868 1254
92740868 get 38 friends
92740868 get 38 friends done
860276203126697984 1255
860276203126697984 get 333 friends
860276203126697984 get 333 friends done
166598394 1256
166598394 get 11715 friends
166598394 get 11715 friends done
761499948890329088 1257
761499948890329088 get 2780 friends
761499948890329088 get 2780 friends done
61862447 1258
61862447 with error
2958634360 1259
2958634360 with error
2872987265 1260
2872987265 get 920 friends
2872987265 get 920 friends done
1608015174 1261
1608015174 get 231 friends
1608015174 get 231 friends done
371201577 1262
371201577 get 5351 friends
371201577 get 5351 friends done
16134235 1263
16134235 get 7302 friends
16134235 get 7302 friends done
1080905119 1264

1080905119 get 2290 friends
1080905119 get 2290 friends done
855132236944994304 1265
855132236944994304 with error
2857724140 1266
2857724140 get 314 friends
2857724140 get 314 friends done
796327176547291136 1267
796327176547291136 get 138 friends
796327176547291136 get 138 friends done
859158116344229888 1268
859158116344229888 get 274 friends
859158116344229888 get 274 friends done
804596460 1269
804596460 get 7200 friends
804596460 get 7200 friends done
2885995521 1270
2885995521 get 159 friends
2885995521 get 159 friends done
49619469 1271
49619469 get 6266 friends
49619469 get 6266 friends done
529709785 1272
529709785 get 820 friends
529709785 get 820 friends done
862761202627338240 1273
862761202627338240 with error
296942850 1274
296942850 get 695 friends
296942850 get 695 friends done
38671387 1275
38671387 get 4079 friends
38671387 get 4079 friends done
707157228516724736 1276
707157228516724736 get 494 friends
707157228516724736 get 494 friends done
31184038 1277
31184038 with error
232276399 1278
232276399 get 949 friends
232276399 get 949 friends done
3164087579 1279
3164087579 get 2470 friends
3164087579 get 2470 friends done
861288310894977024 1280
861288310894977024 with error
2173779986 1281
2173779986 get 9075 friends
2173779986 get 9075 friends done
2382227424 1282
2382227424 get 21813 friends
2382227424 get 21813 friends done
732884834163544064 1283
732884834163544064 get 851 friends
732884834163544064 get 851 friends done
212209552 1284
212209552 get 3173 friends
212209552 get 3173 friends done
856237016425562112 1285
856237016425562112 get 159 friends
856237016425562112 get 159 friends done
43865757 1286
43865757 get 3905 friends
43865757 get 3905 friends done
3092429597 1287
3092429597 get 5405 friends
3092429597 get 5405 friends done
355511046 1288
355511046 get 1008 friends
355511046 get 1008 friends done
103879974 1289
103879974 get 12543 friends
103879974 get 12543 friends done
1249324855 1290
1249324855 get 70 friends
1249324855 get 70 friends done
860159801057214464 1291
860159801057214464 with error
460401829 1292
460401829 get 36707 friends
460401829 get 36707 friends done
18020612 1293
18020612 with error
787410402560925696 1294
787410402560925696 with error
859085802218893312 1295
859085802218893312 get 306 friends
859085802218893312 get 306 friends done
863136661 1296
863136661 get 5514 friends
863136661 get 5514 friends done
97675014 1297
97675014 with error
224655400 1298
224655400 get 22021 friends
224655400 get 22021 friends done
345215801 1299
345215801 get 1659 friends
345215801 get 1659 friends done
56999787 1300

In [ ]:
new_list_id[49]

In [9]:
def Get_degree(userid = 1603153040):
    record = []
    try:
        friend_list = api.GetFollowers(user_id = userid)
    except:
        deadlist.append(userid)
        print(str(userid) + ' with error')
        return 
   
    print('{} get {} friends'.format(userid, len(friend_list)))
    friend_degree = []
    follower_degree = []
    for users in friend_list:

        followers =  users._json.get('followers_count')
        friends =  users._json.get('friends_count')
        friend_degree.append(friends)
        follower_degree.append(followers)
    avg_fr = sum(friend_degree)/len(friend_list)
    max_fr = max(friend_degree)
    min_fr = min(friend_degree)
    avg_fo = sum(follower_degree)/len(friend_list)
    max_fo = max(follower_degree)
    min_fo = min(follower_degree)
    var_fr = np.var(friend_degree)
    var_fo = np.var(follower_degree)
    record = [userid, avg_fr, max_fr, min_fr, var_fr, avg_fo, max_fo, min_fo, var_fo]
    print('{} get {} friends done'.format(userid, len(friend_list)))
    with open('neighbor_information_17_1000.csv', 'a') as myfile:
        myfile.write('{}\n'.format(','.join(map(str,record))))
    return record

In [34]:
Get_degree(71084757)

71084757 with error

[]

In [10]:
deadlist = []

In [20]:
deadlist.append(new_list_id[49])

In [ ]:
deadlist

In [1]:
count

NameError: name 'count' is not defined

In [13]:
new_list_id[1145]

14284260